refactor：sendrule model property change
masastack/MASA.BuildingBlocks pull request #116
Opened 2022-07-25 03:38 UTC by wzh425

# Description

refactor：sendrule model property change

2022-07-25 03:41 UTC, zhenlei520 approved these changes
@doddgu

2022-07-26 01:19 UTC, doddgu requested changes

2022-07-26 01:19 UTC, doddgu commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Model/SendRuleModel.cs
> +    public bool IsCustom { get; set; }
Add blank line between properties.

2022-07-26 01:36 UTC, doddgu approved these changes
LGTM

2022-07-26 01:36 UTC, merged