feature(OIDC):add oidc
masastack/MASA.BuildingBlocks pull request #66
Opened 2022-06-13 07:12 UTC by 15168440402

2022-06-14 03:11 UTC, zhenlei520 commented on src/Oidc/Masa.BuildingBlocks.Oidc.Models/Models/PersistedGrantModel.cs
> +    public PersistedGrantModel(string key, string type, string subjectId, string sessionId, string clientId, string description, DateTime creationTime, DateTime? expiration, DateTime? consumedTime, s
line break recommended

2022-06-14 03:11 UTC, zhenlei520 commented on src/Oidc/Masa.BuildingBlocks.Oidc.Models/Models/IdentityResourceModel.cs
> +    public IdentityResourceModel(string name, string displayName, string? description, bool enabled, bool showInDiscoveryDocument, bool required, bool emphasize, ICollection<string> userClaims, IDict
line break recommended

2022-06-14 08:36 UTC, zhenlei520 commented on src/Oidc/Masa.BuildingBlocks.Oidc.Models/Models/ClientClaimModel.cs
> +    /// <param name="value"></param>
If there is no description, it is recommended to remove

2022-06-14 08:36 UTC, zhenlei520 commented on src/Oidc/Masa.BuildingBlocks.Oidc.Models/Models/IdentityResourceModel.cs
> +        Properties = properties;
Properties is a non-null value

2022-06-14 08:38 UTC, zhenlei520 commented on src/Oidc/Masa.BuildingBlocks.Oidc.Domain/Repositories/IRepositoryBase.cs
> +public interface IRepositoryBase<TEntity> where TEntity : class, IEntity
@doddgu At present, what we define starts with Base, but it is better for some services to end with Base ( `ServiceBase`, `ControllerBase` ), does this need to be unified again?

2022-06-15 02:04 UTC, zhenlei520 approved these changes
@doddgu 
LGTM

2022-06-20 08:01 UTC, doddgu requested changes

2022-06-20 08:01 UTC, doddgu commented on src/Authentication/Masa.BuildingBlocks.Authentication.Oidc.Models/Models/GrantType.cs
> +    public const string Implicit = "implicit";
Upper.

2022-06-20 09:11 UTC, doddgu approved these changes
LGTM

2022-06-20 09:11 UTC, merged