feat：mc sdk & sdk unit test
masastack/MASA.BuildingBlocks pull request #83
Opened 2022-06-29 10:09 UTC by wzh425

# Description

mc sdk & sdk unit test

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Infrastructure/Extensions/DictionaryExtensions.cs
> +    public static TValue GetOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)
return type is nullable

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Infrastructure/Extensions/DictionaryExtensions.cs
> +    public static TValue GetOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key)
same as above

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Infrastructure/Extensions/DictionaryExtensions.cs
> +    public static TValue GetOrDefault<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary, TKey key)
same as above

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Infrastructure/Extensions/DictionaryExtensions.cs
> +    public static TValue GetOrAdd<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary, TKey key, Func<TValue> factory)
where TKey : notnull

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageEntityTypes.cs
> +public enum MessageEntityTypes
Not a good name

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageTaskReceiverTypes.cs
> +public enum MessageTaskReceiverTypes
Not a good name

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageTaskSelectReceiverTypes.cs
> +public enum MessageTaskSelectReceiverTypes
Not a good name

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageTaskStatuses.cs
> +    WaitSend = 1,
NotPublished、InProgress、Cancel、Published、PublishedFailed、PartialFailed

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageTemplateAuditStatuses.cs
> +    Fail,
Waited、Approved、Failed

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/MessageTemplateStatuses.cs
> +public enum MessageTemplateStatuses
MessageTemplateStates

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/ReceiverTypes.cs
> +public enum ReceiverTypes
not a good name

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Enum/WebsiteMessageFilterType.cs
> +    MessageTitle = 1,
Title、Content

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Infrastructure/Helper/TypeHelper.cs
> +    public static object GetDefaultValue(Type type)
nullable return type

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/Model/GetChannelModel.cs
> +    public string Filter { get; set; } = string.Empty;
Format Code

2022-06-30 01:49 UTC, zhenlei520 commented on src/BasicAbility/Masa.BuildingBlocks.BasicAbility.Mc/_import.cs
> +global using Masa.BuildingBlocks.BasicAbility.Mc.Enum;
Sort

2022-07-04 01:17 UTC, doddgu requested changes

2022-07-04 01:34 UTC, doddgu approved these changes
LGTM

2022-07-04 01:34 UTC, merged